/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * CRM.Backend.Web | v1
 * OpenAPI spec version: 1.0.0
 */

export interface GroupingInfo {
	groupInterval?: unknown;
	/** @nullable */
	isExpanded?: boolean | null;
	/** @nullable */
	selector?: string | null;
	desc?: boolean;
}
