/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * CRM.Backend.Web | v1
 * OpenAPI spec version: 1.0.0
 */

export interface GroupMemberDto {
	id?: string;
	groupId?: string;
	workspaceUserId?: string;
	addedAt?: string;
	isActive?: boolean;
}
