/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * CRM.Backend.Web | v1
 * OpenAPI spec version: 1.0.0
 */

export interface InfoRequest {
	/** @nullable */
	newEmail?: string | null;
	/** @nullable */
	newPassword?: string | null;
	/** @nullable */
	oldPassword?: string | null;
}
