/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * CRM.Backend.Web | v1
 * OpenAPI spec version: 1.0.0
 */

export interface MessageDto {
	id?: string;
	conversationId?: string;
	content?: string;
	sentAt?: string;
	/** @nullable */
	mediaUrl?: string | null;
	/** @nullable */
	mediaType?: string | null;
	senderId?: string;
	workspaceId?: string;
	/** @nullable */
	repliedMessageId?: string | null;
}
