/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * CRM.Backend.Web | v1
 * OpenAPI spec version: 1.0.0
 */

export interface MetricBreakdown {
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	tasksCompleted?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	projectsActive?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
	hoursWorked?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
	score?: number | string;
}
