/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * CRM.Backend.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationType } from "./notificationType";

export interface NotificationDto {
	id?: string;
	title?: string;
	message?: string;
	type?: NotificationType;
	isRead?: boolean;
	/** @nullable */
	actionUrl?: string | null;
	/** @nullable */
	icon?: string | null;
	userId?: string;
	/** @nullable */
	relatedEntityId?: string | null;
	/** @nullable */
	relatedEntityType?: string | null;
	/** @nullable */
	readAt?: string | null;
}
