/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * CRM.Backend.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { IFormFile } from "./iFormFile";

export type PostApiMediaUploadBody = {
	file: IFormFile;
};
