/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * CRM.Backend.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { MetricBreakdown } from "./metricBreakdown";
import type { SubordinateProductivityDto } from "./subordinateProductivityDto";

export interface ProductivityReportDto {
	name?: string;
	/** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
	efficiencyScore?: number | string;
	current?: MetricBreakdown;
	previousPeriod?: MetricBreakdown;
	previousYear?: MetricBreakdown;
	subordinates?: SubordinateProductivityDto[];
}
