/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * CRM.Backend.Web | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ReportShareDto {
	id?: string;
	shareToken?: string;
	isPublic?: boolean;
	/** @nullable */
	expiresAt?: string | null;
	isActive?: boolean;
	reportId?: string;
	sharedById?: string;
	/** @nullable */
	sharedWithId?: string | null;
}
