/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * CRM.Backend.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ReportStatus } from "./reportStatus";
import type { ReportType } from "./reportType";

export interface ReportDto {
	id?: string;
	name?: string;
	/** @nullable */
	description?: string | null;
	type?: ReportType;
	configuration?: string;
	/** @nullable */
	filePath?: string | null;
	status?: ReportStatus;
	/** @nullable */
	generatedAt?: string | null;
	isScheduled?: boolean;
	/** @nullable */
	scheduleCron?: string | null;
	/** @nullable */
	nextRunAt?: string | null;
	/** @nullable */
	workspaceId?: string | null;
}
