/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * CRM.Backend.Web | v1
 * OpenAPI spec version: 1.0.0
 */

export interface SendMailCommand {
	host?: string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	port?: number | string;
	user?: string;
	password?: string;
	useSsl?: boolean;
	to?: string;
	subject?: string;
	body?: string;
}
