/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * CRM.Backend.Web | v1
 * OpenAPI spec version: 1.0.0
 */

export interface TaskCategoryDto {
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	id?: number | string;
	name?: string;
	/** @nullable */
	description?: string | null;
	color?: string;
	/** @nullable */
	icon?: string | null;
	isActive?: boolean;
}
