/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * CRM.Backend.Web | v1
 * OpenAPI spec version: 1.0.0
 */

export interface TwoFactorResponse {
	sharedKey: string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	recoveryCodesLeft: number | string;
	/** @nullable */
	recoveryCodes?: string[] | null;
	isTwoFactorEnabled: boolean;
	isMachineRemembered: boolean;
}
