/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * CRM.Backend.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { WorkSpaceTaskStatus } from "./workSpaceTaskStatus";

export interface WorkspaceTaskDto {
	id?: string;
	title?: string;
	/** @nullable */
	description?: string | null;
	startDate?: string;
	endDate?: string;
	workspaceTaskStatus?: WorkSpaceTaskStatus;
	workspaceId?: string;
	projectId?: string;
}
